# Generated by Django 2.1.5 on 2019-02-02 14:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Kindergartens',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PrimarySchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Primary schools',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='primary_schools',
            field=models.ManyToManyField(to='schools.PrimarySchool'),
        ),
    ]
