# Generated by Django 2.2.4 on 2019-08-02 16:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Kindergartens',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PrimarySchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('kindergartens', models.ManyToManyField(blank=True, to='schools.Kindergarten')),
            ],
            options={
                'verbose_name_plural': 'Primary schools',
                'ordering': ('name',),
            },
        ),
    ]
