# Generated by Django 2.1.5 on 2019-01-17 08:25

from django.db import migrations
from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [

    ]
