# Generated by Django 2.1.5 on 2019-01-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20190117_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('name',), 'verbose_name_plural': 'schools'},
        ),
        migrations.RenameField(
            model_name='school',
            old_name='location',
            new_name='geometry',
        ),
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_type',
        ),
    ]
