# Generated by Django 2.1.5 on 2019-03-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20190228_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kindergarten',
            name='primary_schools',
        ),
        migrations.AddField(
            model_name='primaryschool',
            name='kindergartens',
            field=models.ManyToManyField(blank=True, to='schools.Kindergarten'),
        ),
    ]
