# Generated by Django 2.2.4 on 2019-10-21 15:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_registrationresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=6, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=8, null=True)),
                ('email_address', models.CharField(blank=True, max_length=100, null=True)),
                ('website_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
