# Generated by Django 2.2.4 on 2019-10-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='collocated_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Place'),
        ),
    ]
