# Generated by Django 2.2.4 on 2019-10-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20191021_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationresults',
            options={'ordering': ('place', 'year'), 'verbose_name_plural': 'Registration Results'},
        ),
        migrations.RemoveField(
            model_name='registrationresults',
            name='primaryschool',
        ),
        migrations.AddField(
            model_name='registrationresults',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.Place'),
            preserve_default=False,
        ),
    ]
