# Generated by Django 2.2.4 on 2020-04-14 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20191021_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneMapToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('expiryTimeStamp', models.BigIntegerField()),
                ('modifiedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='primaryschool',
            name='kindergartens',
        ),
        migrations.DeleteModel(
            name='SecondarySchool',
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('name',)},
        ),
        migrations.DeleteModel(
            name='Kindergarten',
        ),
        migrations.DeleteModel(
            name='PrimarySchool',
        ),
    ]
